---
- hosts: all
  gather_facts: no
  tasks:
  - name: stop container
    command: docker container stop c1
    ignore_errors: yes

  - name: delete container
    command: docker container rm c1
    ignore_errors: yes

  - name: remove image
    command: docker image rm subodhdere77/mytom:{{BUILD_NUMBER}}
    ignore_errors: yes

  - name: create container c1
    command: docker container run -d --name c1 -p 8888:8080 subodhdere77/mytom:{{BUILD_NUMBER}}
